/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type ProductVariant = {
  _type: "productVariant";
  colorName?: string;
  colorImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  sizes?: Array<{
    size?: "XXS" | "XS" | "S" | "M" | "L" | "XL" | "XXL";
    stock?: number;
    sku?: string;
    _type: "sizeOption";
    _key: string;
  }>;
  variantImages?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
};

export type Header = {
  _id: string;
  _type: "header";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  freeShippingText?: string;
  leftNavLinks?: Array<{
    label?: string;
    href?: string;
    _key: string;
  }>;
  rightNavLinks?: Array<{
    label?: string;
    href?: string;
    _key: string;
  }>;
};

export type ShoppablePost = {
  _id: string;
  _type: "shoppablePost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  profileImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  category?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "storyCategory";
  };
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  caption?: string;
  hashtags?: Array<string>;
  instagramUrl?: string;
  productTags?: Array<{
    product?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "product";
    };
    _type: "productTag";
    _key: string;
  }>;
  publishedAt?: string;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  thumbnail?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  price?: number;
  compareAtPrice?: number;
  currency?: "USD" | "EUR" | "GBP" | "TRY";
  variants?: Array<{
    _key: string;
  } & ProductVariant>;
  shopUrl?: string;
  brand?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "brand";
  };
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type StoryCategory = {
  _id: string;
  _type: "storyCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  thumbnail?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  brand?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "brand";
  };
  order?: number;
  orderRank?: string;
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  displayName?: string;
  slug?: Slug;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  instagramHandle?: string;
  instagramUrl?: string;
  sectionTitle?: string;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = ProductVariant | Header | ShoppablePost | SanityImageCrop | SanityImageHotspot | Product | Slug | StoryCategory | Brand | Code | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./app/sitemap.ts
// Variable: pagesQuery
// Query: *[_type == 'page'] | order(slug.current) {      'url': $baseUrl + select(slug.current == 'index' => '', '/' + slug.current),      'lastModified': _updatedAt,      'changeFrequency': 'daily',      'priority': select(        slug.current == 'index' => 1,        0.5      )    }
export type PagesQueryResult = Array<never>;
// Variable: postsQuery
// Query: *[_type == 'post'] | order(_updatedAt desc) {      'url': $baseUrl + '/blog/' + slug.current,      'lastModified': _updatedAt,      'changeFrequency': 'weekly',      'priority': 0.7    }
export type PostsQueryResult = Array<never>;

// Source: ./sanity/queries/shoppable-stories.ts
// Variable: FIRST_BRAND_WITH_CATEGORIES_QUERY
// Query: *[_type == "brand"][0] {    _id,    name,    displayName,    "logoUrl": logo.asset->url,    instagramHandle,    instagramUrl,    sectionTitle,    "categories": *[_type == "storyCategory" && brand._ref == ^._id] | order(order asc) {      _id,      name,      "slug": slug.current,      "thumbnailUrl": thumbnail.asset->url,      "postCount": count(*[_type == "shoppablePost" && category._ref == ^._id])    }  }
export type FIRST_BRAND_WITH_CATEGORIES_QUERYResult = {
  _id: string;
  name: string | null;
  displayName: string | null;
  logoUrl: string | null;
  instagramHandle: string | null;
  instagramUrl: string | null;
  sectionTitle: string | null;
  categories: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    thumbnailUrl: string | null;
    postCount: number;
  }>;
} | null;
// Variable: BRAND_WITH_CATEGORIES_QUERY
// Query: *[_type == "brand" && slug.current == $brandSlug][0] {    _id,    name,    displayName,    "logoUrl": logo.asset->url,    instagramHandle,    instagramUrl,    sectionTitle,    "categories": *[_type == "storyCategory" && brand._ref == ^._id] | order(order asc) {      _id,      name,      "slug": slug.current,      "thumbnailUrl": thumbnail.asset->url,      gradientColors,      "postCount": count(*[_type == "shoppablePost" && category._ref == ^._id])    }  }
export type BRAND_WITH_CATEGORIES_QUERYResult = {
  _id: string;
  name: string | null;
  displayName: string | null;
  logoUrl: string | null;
  instagramHandle: string | null;
  instagramUrl: string | null;
  sectionTitle: string | null;
  categories: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    thumbnailUrl: string | null;
    gradientColors: null;
    postCount: number;
  }>;
} | null;
// Variable: ALL_BRANDS_QUERY
// Query: *[_type == "brand"] | order(name asc) {    _id,    name,    displayName,    "slug": slug.current,    "logoUrl": logo.asset->url,    instagramHandle,    sectionTitle  }
export type ALL_BRANDS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  displayName: string | null;
  slug: string | null;
  logoUrl: string | null;
  instagramHandle: string | null;
  sectionTitle: string | null;
}>;
// Variable: CATEGORY_WITH_POSTS_QUERY
// Query: *[_type == "storyCategory" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    "thumbnailUrl": thumbnail.asset->url,    gradientColors,    brand-> {      _id,      name,      displayName,      "logoUrl": logo.asset->url,      instagramHandle    },    "posts": *[_type == "shoppablePost" && category._ref == ^._id] | order(order asc) {      _id,      title,      "imageUrl": mainImage.asset->url,      "profileImageUrl": profileImage.asset->url,      brandName,      caption,      hashtags,      instagramUrl,      productTags[] {        _key,        x,        y,        product-> {          _id,          title,          "slug": slug.current,          price,          compareAtPrice,          currency,          "thumbnailUrl": thumbnail.asset->url,          shopUrl,          variants[] {            _key,            colorName,            "colorImageUrl": colorImage.asset->url,            sizes[] {              _key,              size,              stock            }          }        }      }    },    "postCount": count(*[_type == "shoppablePost" && category._ref == ^._id])  }
export type CATEGORY_WITH_POSTS_QUERYResult = {
  _id: string;
  name: string | null;
  slug: string | null;
  thumbnailUrl: string | null;
  gradientColors: null;
  brand: {
    _id: string;
    name: string | null;
    displayName: string | null;
    logoUrl: string | null;
    instagramHandle: string | null;
  } | null;
  posts: Array<{
    _id: string;
    title: string | null;
    imageUrl: string | null;
    profileImageUrl: string | null;
    brandName: null;
    caption: string | null;
    hashtags: Array<string> | null;
    instagramUrl: string | null;
    productTags: Array<{
      _key: string;
      x: null;
      y: null;
      product: {
        _id: string;
        title: string | null;
        slug: string | null;
        price: number | null;
        compareAtPrice: number | null;
        currency: "EUR" | "GBP" | "TRY" | "USD" | null;
        thumbnailUrl: string | null;
        shopUrl: string | null;
        variants: Array<{
          _key: string;
          colorName: string | null;
          colorImageUrl: string | null;
          sizes: Array<{
            _key: string;
            size: "L" | "M" | "S" | "XL" | "XS" | "XXL" | "XXS" | null;
            stock: number | null;
          }> | null;
        }> | null;
      } | null;
    }> | null;
  }>;
  postCount: number;
} | null;
// Variable: CATEGORY_SLUGS_QUERY
// Query: *[_type == "storyCategory"]{ "slug": slug.current }
export type CATEGORY_SLUGS_QUERYResult = Array<{
  slug: string | null;
}>;
// Variable: PRODUCT_QUERY
// Query: *[_type == "product" && slug.current == $productSlug][0] {    _id,    title,    "slug": slug.current,    price,    compareAtPrice,    currency,    "thumbnailUrl": thumbnail.asset->url,    "images": images[].asset->url,    shopUrl,    variants[] {      _key,      colorName,      "colorImageUrl": colorImage.asset->url,      sizes[] {        _key,        size,        stock,        sku      },      "variantImages": variantImages[].asset->url    },    brand-> {      _id,      name,      displayName    }  }
export type PRODUCT_QUERYResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  compareAtPrice: number | null;
  currency: "EUR" | "GBP" | "TRY" | "USD" | null;
  thumbnailUrl: string | null;
  images: Array<string | null> | null;
  shopUrl: string | null;
  variants: Array<{
    _key: string;
    colorName: string | null;
    colorImageUrl: string | null;
    sizes: Array<{
      _key: string;
      size: "L" | "M" | "S" | "XL" | "XS" | "XXL" | "XXS" | null;
      stock: number | null;
      sku: string | null;
    }> | null;
    variantImages: Array<string | null> | null;
  }> | null;
  brand: {
    _id: string;
    name: string | null;
    displayName: string | null;
  } | null;
} | null;
// Variable: PRODUCT_BY_ID_QUERY
// Query: *[_type == "product" && _id == $productId][0] {    _id,    title,    "slug": slug.current,    price,    compareAtPrice,    currency,    "thumbnailUrl": thumbnail.asset->url,    "images": images[].asset->url,    shopUrl,    variants[] {      _key,      colorName,      "colorImageUrl": colorImage.asset->url,      sizes[] {        _key,        size,        stock,        sku      },      "variantImages": variantImages[].asset->url    }  }
export type PRODUCT_BY_ID_QUERYResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  compareAtPrice: number | null;
  currency: "EUR" | "GBP" | "TRY" | "USD" | null;
  thumbnailUrl: string | null;
  images: Array<string | null> | null;
  shopUrl: string | null;
  variants: Array<{
    _key: string;
    colorName: string | null;
    colorImageUrl: string | null;
    sizes: Array<{
      _key: string;
      size: "L" | "M" | "S" | "XL" | "XS" | "XXL" | "XXS" | null;
      stock: number | null;
      sku: string | null;
    }> | null;
    variantImages: Array<string | null> | null;
  }> | null;
} | null;
// Variable: ALL_PRODUCTS_QUERY
// Query: *[_type == "product"] | order(title asc) {    _id,    title,    "slug": slug.current,    price,    compareAtPrice,    currency,    "thumbnailUrl": thumbnail.asset->url,    brand-> {      _id,      displayName    }  }
export type ALL_PRODUCTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  compareAtPrice: number | null;
  currency: "EUR" | "GBP" | "TRY" | "USD" | null;
  thumbnailUrl: string | null;
  brand: {
    _id: string;
    displayName: string | null;
  } | null;
}>;
// Variable: SHOPPABLE_POST_QUERY
// Query: *[_type == "shoppablePost" && _id == $postId][0] {    _id,    title,    "imageUrl": mainImage.asset->url,    "imageAspectRatio": mainImage.asset->metadata.dimensions.aspectRatio,    caption,    hashtags,    instagramUrl,    category-> {      _id,      name,      "slug": slug.current,      brand-> {        _id,        displayName,        "logoUrl": logo.asset->url      }    },    productTags[] {      _key,      x,      y,      product-> {        _id,        title,        "slug": slug.current,        price,        compareAtPrice,        currency,        "thumbnailUrl": thumbnail.asset->url,        shopUrl,        variants[] {          _key,          colorName,          "colorImageUrl": colorImage.asset->url,          sizes[] {            _key,            size,            stock,            sku          }        }      }    }  }
export type SHOPPABLE_POST_QUERYResult = {
  _id: string;
  title: string | null;
  imageUrl: string | null;
  imageAspectRatio: number | null;
  caption: string | null;
  hashtags: Array<string> | null;
  instagramUrl: string | null;
  category: {
    _id: string;
    name: string | null;
    slug: string | null;
    brand: {
      _id: string;
      displayName: string | null;
      logoUrl: string | null;
    } | null;
  } | null;
  productTags: Array<{
    _key: string;
    x: null;
    y: null;
    product: {
      _id: string;
      title: string | null;
      slug: string | null;
      price: number | null;
      compareAtPrice: number | null;
      currency: "EUR" | "GBP" | "TRY" | "USD" | null;
      thumbnailUrl: string | null;
      shopUrl: string | null;
      variants: Array<{
        _key: string;
        colorName: string | null;
        colorImageUrl: string | null;
        sizes: Array<{
          _key: string;
          size: "L" | "M" | "S" | "XL" | "XS" | "XXL" | "XXS" | null;
          stock: number | null;
          sku: string | null;
        }> | null;
      }> | null;
    } | null;
  }> | null;
} | null;
// Variable: HEADER_QUERY
// Query: *[_type == "header"][0] {    freeShippingText,    leftNavLinks[] {      label,      href    },    rightNavLinks[] {      label,      href    }  }
export type HEADER_QUERYResult = {
  freeShippingText: string | null;
  leftNavLinks: Array<{
    label: string | null;
    href: string | null;
  }> | null;
  rightNavLinks: Array<{
    label: string | null;
    href: string | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n    *[_type == 'page'] | order(slug.current) {\n      'url': $baseUrl + select(slug.current == 'index' => '', '/' + slug.current),\n      'lastModified': _updatedAt,\n      'changeFrequency': 'daily',\n      'priority': select(\n        slug.current == 'index' => 1,\n        0.5\n      )\n    }\n  ": PagesQueryResult;
    "\n    *[_type == 'post'] | order(_updatedAt desc) {\n      'url': $baseUrl + '/blog/' + slug.current,\n      'lastModified': _updatedAt,\n      'changeFrequency': 'weekly',\n      'priority': 0.7\n    }\n  ": PostsQueryResult;
    "\n  *[_type == \"brand\"][0] {\n    _id,\n    name,\n    displayName,\n    \"logoUrl\": logo.asset->url,\n    instagramHandle,\n    instagramUrl,\n    sectionTitle,\n    \"categories\": *[_type == \"storyCategory\" && brand._ref == ^._id] | order(order asc) {\n      _id,\n      name,\n      \"slug\": slug.current,\n      \"thumbnailUrl\": thumbnail.asset->url,\n      \"postCount\": count(*[_type == \"shoppablePost\" && category._ref == ^._id])\n    }\n  }\n": FIRST_BRAND_WITH_CATEGORIES_QUERYResult;
    "\n  *[_type == \"brand\" && slug.current == $brandSlug][0] {\n    _id,\n    name,\n    displayName,\n    \"logoUrl\": logo.asset->url,\n    instagramHandle,\n    instagramUrl,\n    sectionTitle,\n    \"categories\": *[_type == \"storyCategory\" && brand._ref == ^._id] | order(order asc) {\n      _id,\n      name,\n      \"slug\": slug.current,\n      \"thumbnailUrl\": thumbnail.asset->url,\n      gradientColors,\n      \"postCount\": count(*[_type == \"shoppablePost\" && category._ref == ^._id])\n    }\n  }\n": BRAND_WITH_CATEGORIES_QUERYResult;
    "\n  *[_type == \"brand\"] | order(name asc) {\n    _id,\n    name,\n    displayName,\n    \"slug\": slug.current,\n    \"logoUrl\": logo.asset->url,\n    instagramHandle,\n    sectionTitle\n  }\n": ALL_BRANDS_QUERYResult;
    "\n  *[_type == \"storyCategory\" && slug.current == $slug][0] {\n    _id,\n    name,\n    \"slug\": slug.current,\n    \"thumbnailUrl\": thumbnail.asset->url,\n    gradientColors,\n    brand-> {\n      _id,\n      name,\n      displayName,\n      \"logoUrl\": logo.asset->url,\n      instagramHandle\n    },\n    \"posts\": *[_type == \"shoppablePost\" && category._ref == ^._id] | order(order asc) {\n      _id,\n      title,\n      \"imageUrl\": mainImage.asset->url,\n      \"profileImageUrl\": profileImage.asset->url,\n      brandName,\n      caption,\n      hashtags,\n      instagramUrl,\n      productTags[] {\n        _key,\n        x,\n        y,\n        product-> {\n          _id,\n          title,\n          \"slug\": slug.current,\n          price,\n          compareAtPrice,\n          currency,\n          \"thumbnailUrl\": thumbnail.asset->url,\n          shopUrl,\n          variants[] {\n            _key,\n            colorName,\n            \"colorImageUrl\": colorImage.asset->url,\n            sizes[] {\n              _key,\n              size,\n              stock\n            }\n          }\n        }\n      }\n    },\n    \"postCount\": count(*[_type == \"shoppablePost\" && category._ref == ^._id])\n  }\n": CATEGORY_WITH_POSTS_QUERYResult;
    "\n  *[_type == \"storyCategory\"]{ \"slug\": slug.current }\n": CATEGORY_SLUGS_QUERYResult;
    "\n  *[_type == \"product\" && slug.current == $productSlug][0] {\n    _id,\n    title,\n    \"slug\": slug.current,\n    price,\n    compareAtPrice,\n    currency,\n    \"thumbnailUrl\": thumbnail.asset->url,\n    \"images\": images[].asset->url,\n    shopUrl,\n    variants[] {\n      _key,\n      colorName,\n      \"colorImageUrl\": colorImage.asset->url,\n      sizes[] {\n        _key,\n        size,\n        stock,\n        sku\n      },\n      \"variantImages\": variantImages[].asset->url\n    },\n    brand-> {\n      _id,\n      name,\n      displayName\n    }\n  }\n": PRODUCT_QUERYResult;
    "\n  *[_type == \"product\" && _id == $productId][0] {\n    _id,\n    title,\n    \"slug\": slug.current,\n    price,\n    compareAtPrice,\n    currency,\n    \"thumbnailUrl\": thumbnail.asset->url,\n    \"images\": images[].asset->url,\n    shopUrl,\n    variants[] {\n      _key,\n      colorName,\n      \"colorImageUrl\": colorImage.asset->url,\n      sizes[] {\n        _key,\n        size,\n        stock,\n        sku\n      },\n      \"variantImages\": variantImages[].asset->url\n    }\n  }\n": PRODUCT_BY_ID_QUERYResult;
    "\n  *[_type == \"product\"] | order(title asc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    price,\n    compareAtPrice,\n    currency,\n    \"thumbnailUrl\": thumbnail.asset->url,\n    brand-> {\n      _id,\n      displayName\n    }\n  }\n": ALL_PRODUCTS_QUERYResult;
    "\n  *[_type == \"shoppablePost\" && _id == $postId][0] {\n    _id,\n    title,\n    \"imageUrl\": mainImage.asset->url,\n    \"imageAspectRatio\": mainImage.asset->metadata.dimensions.aspectRatio,\n    caption,\n    hashtags,\n    instagramUrl,\n    category-> {\n      _id,\n      name,\n      \"slug\": slug.current,\n      brand-> {\n        _id,\n        displayName,\n        \"logoUrl\": logo.asset->url\n      }\n    },\n    productTags[] {\n      _key,\n      x,\n      y,\n      product-> {\n        _id,\n        title,\n        \"slug\": slug.current,\n        price,\n        compareAtPrice,\n        currency,\n        \"thumbnailUrl\": thumbnail.asset->url,\n        shopUrl,\n        variants[] {\n          _key,\n          colorName,\n          \"colorImageUrl\": colorImage.asset->url,\n          sizes[] {\n            _key,\n            size,\n            stock,\n            sku\n          }\n        }\n      }\n    }\n  }\n": SHOPPABLE_POST_QUERYResult;
    "\n  *[_type == \"header\"][0] {\n    freeShippingText,\n    leftNavLinks[] {\n      label,\n      href\n    },\n    rightNavLinks[] {\n      label,\n      href\n    }\n  }\n": HEADER_QUERYResult;
  }
}
